import pandas as pd
import numpy as np

df1 = pd.DataFrame(np.random.randn(5, 4), columns=list('ABCD'), index=pd.date_range('20190701', periods=5))
print("df1")
print(df1)
print()
print(df1.loc['20190702':'20190704'])
print()
print(df1.iloc[0])
print()
print(df1['A'])
print()
print()

ser1 = pd.Series(np.random.randn(4), index=list('abcd'))
print("ser1")
print(ser1)
print()
print(ser1.loc['b'])
print()
print(ser1.loc['c'])
print()
ser1.loc['c'] = 0
print(ser1)
print()
ser1[2:] = 30
print(ser1)
print()
print("----------------------------")
print()

df2 = pd.DataFrame(np.random.randn(5, 4), columns=list('ABCD'), index=list("abcde"))
print("df2")
print(df2)
print()
print(df2.loc[['a', 'b', 'd'], :])
print()
print(df2.loc[['a', 'b', 'd'], "B":"D"])
print()
print(df2.loc[['a', 'b', 'd'], ["B", "D"]])
print()
print()

ser2 = pd.Series(list("abcde"), index=[0, 3, 2, 5, 4])
print("ser2")
print(ser2)
print()
print(ser2.loc[0:2])
print()
print(ser2.iloc[0:2])
print()
print()
ser3 = pd.Series(list("abcde"))
print("ser3")
print(ser3)
print()
print(ser3.loc[0:2])
print()
ser4 = ser2.sort_index()
print("ser4")
print(ser4)
print()
ser5 = ser2.sort_values()
print("ser5")
print(ser5)
print()
print("-------------------")
print()

df3 = pd.DataFrame(np.random.randn(5, 4), columns=list(range(0, 8, 2)), index=list(range(0, 10, 2)))
print("df3")
print(df3)
print()
print(df3.loc[0:4, 2:6])
print()
print(df3.iloc[0:3, 1:4])
print()
print(df3.iloc[0:3])
print()
print(df3.iloc[:, 1:])
print()
print(df3.iloc[[0, 3], [1, 2]])
print()
print()

df4 = pd.DataFrame(np.random.randn(5, 4), columns=list("ABCE"), index=list("abcde"))
print("df4")
print(df4)
print()
print(df4.loc[lambda df:df.A > 0])
print()
print(df4.loc[:, lambda df:df.loc["a"] > 0])
print()
print("------------------------------")
print()

ser6 = pd.Series(np.arange(3))
print("ser6")
print(ser6)
print()
ser6[5] = 7  # 없는 인덱스에 값 넣으면 그 인덱스만 생김, append와 다름
print(ser6)
print()
for i in range(3, 5):
	ser6[i] = 0
print(ser6)
print()
print()

df5 = pd.DataFrame(np.arange(9).reshape(3, 3), columns=list("ABC"))
print("df5")
print(df5)
print()
df5.loc[:, "T"] = df5.loc[:, "A"]
print(df5)
print()
data1 = list("AWESOME")
df5.loc[:, "G"] = pd.Series(data1)
print(df5)
print()
data2 = [33, 33, 33, "S", 33]
df5.loc[0, :] = pd.Series(data2)
print(df5)
print()
df5.loc[0, :] = data2
print(df5)
print()
print(df5["A"])
print()
print(df5.A)  # 영어만 가능
print()
print(df5.isna())
print()
print(df5.notna())
print()
print()
print()
print()
print()
print()
